[2024-10-14T05:03:21.565+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-14T05:03:21.578+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_ml_pipeline.EvaluateModel manual__2024-10-14T04:47:44.141159+00:00 [queued]>
[2024-10-14T05:03:21.585+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_ml_pipeline.EvaluateModel manual__2024-10-14T04:47:44.141159+00:00 [queued]>
[2024-10-14T05:03:21.585+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-14T05:03:21.598+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): EvaluateModel> on 2024-10-14 04:47:44.141159+00:00
[2024-10-14T05:03:21.609+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=7801) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-14T05:03:21.610+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_ml_pipeline', 'EvaluateModel', 'manual__2024-10-14T04:47:44.141159+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/dmc_pipeline.py', '--cfg-path', '/tmp/tmpffuf4498']
[2024-10-14T05:03:21.611+0000] {standard_task_runner.py:72} INFO - Started process 7844 to run task
[2024-10-14T05:03:21.611+0000] {standard_task_runner.py:105} INFO - Job 128: Subtask EvaluateModel
[2024-10-14T05:03:21.647+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_ml_pipeline.EvaluateModel manual__2024-10-14T04:47:44.141159+00:00 [running]> on host 3865df127200
[2024-10-14T05:03:21.719+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_ml_pipeline' AIRFLOW_CTX_TASK_ID='EvaluateModel' AIRFLOW_CTX_EXECUTION_DATE='2024-10-14T04:47:44.141159+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-14T04:47:44.141159+00:00'
[2024-10-14T05:03:21.721+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-14T05:03:21.721+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-14T05:03:21.722+0000] {logging_mixin.py:190} INFO - Current task name:EvaluateModel state:running start_date:2024-10-14 05:03:21.578748+00:00
[2024-10-14T05:03:21.722+0000] {logging_mixin.py:190} INFO - Dag name:kaggle_ml_pipeline and current dag run status:running
[2024-10-14T05:03:21.722+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-14T05:03:21.815+0000] {logging_mixin.py:190} INFO - Modelo cargado desde opt/***/dags/data/model_dmc.joblib
[2024-10-14T05:03:22.482+0000] {logging_mixin.py:190} INFO - Evaluation accuracy: 0.9898030522636201
[2024-10-14T05:03:22.485+0000] {python.py:240} INFO - Done. Returned value was: 0.9898030522636201
[2024-10-14T05:03:22.506+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-14T05:03:22.507+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=kaggle_ml_pipeline, task_id=EvaluateModel, run_id=manual__2024-10-14T04:47:44.141159+00:00, execution_date=20241014T044744, start_date=20241014T050321, end_date=20241014T050322
[2024-10-14T05:03:22.515+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-10-14T05:03:22.515+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-10-14T05:03:22.516+0000] {logging_mixin.py:190} INFO - Dag name:kaggle_ml_pipeline queued_at:2024-10-14 04:47:44.150658+00:00
[2024-10-14T05:03:22.516+0000] {logging_mixin.py:190} INFO - Task hostname:3865df127200 operator:PythonOperator
[2024-10-14T05:03:22.548+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-14T05:03:22.562+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-14T05:03:22.567+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
